# Generated by Django 5.1 on 2024-11-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursales',
            fields=[
                ('Id_Sucursal', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Ubicacion', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=100)),
                ('Horarios', models.CharField(max_length=100)),
                ('Gerente', models.CharField(max_length=100)),
                ('Administracion', models.CharField(max_length=100)),
            ],
        ),
    ]
