# Generated by Django 5.1 on 2024-11-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('salario', models.IntegerField()),
                ('fecha_nacimiento', models.CharField(max_length=100)),
                ('curp', models.CharField(max_length=100)),
                ('RFC', models.CharField(max_length=100)),
            ],
        ),
    ]
