# Generated by Django 5.1 on 2024-11-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.IntegerField(default=100),
        ),
    ]
