# Generated by Django 5.1 on 2024-11-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Nombre', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('Apellidos', models.CharField(max_length=100)),
                ('INE', models.CharField(max_length=100)),
                ('Domicilio', models.CharField(max_length=100)),
                ('Fecha_Nacimiente', models.CharField(max_length=100)),
            ],
        ),
    ]
